# https://spec.openapis.org (메이저 버전간 사양이 다르므로 주의)
###############################################################
# 실행방법 : F1을 누르고 OpenAPI: show preview using Swagger UI를 실행
###############################################################
# https://spec.openapis.org/oas/v3.0.0#schema
# 4.7.1.1 fixed fileds (required : openapi, info, paths)
openapi: "3.0.0"
# https://spec.openapis.org/oas/v3.0.0#infoObject
info:
  title: TODO API Document
  version: "0.0.1"
# https://spec.openapis.org/oas/v3.0.0#pathsObject
paths:
  # https://spec.openapis.org/oas/v3.0.0#pathItemObject
  /health:
    # https://spec.openapis.org/oas/v3.0.0#operationObject
    get:
      responses:
        '200':
          description: OK
  /tasks/1:
    get:
      responses:
        '200':
          description: OK
