# https://spec.openapis.org (메이저 버전간 사양이 다르므로 주의)
###############################################################
# 실행방법 : F1을 누르고 OpenAPI: show preview using Swagger UI를 실행
###############################################################
# https://spec.openapis.org/oas/v3.0.0#schema
# 4.7.1.1 fixed fileds (required : openapi, info, paths)
openapi: "3.0.0"

# https://spec.openapis.org/oas/v3.0.0#infoObject
info:
  title: TODO API Document
  version: "0.0.1"

# swagger ui상에서 tag로 그룹화 가능
tags:
  - name: operations
    description: 運用監視関連API
  - name: tasks
    description: タスク関連API

# https://spec.openapis.org/oas/v3.0.0#pathsObject
paths:
  # https://spec.openapis.org/oas/v3.0.0#pathItemObject
  /health:
    # https://spec.openapis.org/oas/v3.0.0#operationObject
    get:
      tags:
        - operations
      responses:
        '200':
          description: OK
  /tasks/{taskId}:
    get:
      tags:
        - tasks
      operationId: showTask   # 메소드명을 showTask()로 임의지정 (미지정시 tasks1로 메소드명이 지정 됨)
      parameters:
        - name: taskId
          in: path
          required: true
          description: "상세를 취득하는 태스크 아이디"
          schema:
            type: integer
            format: int64 # Long형
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskDTO"
components:
  schemas:
    TaskDTO:
      type: object # json스키마(object)
      properties:
        id:
          type: integer
          format: int64 # long형
          description: "태스크 ID"
        title:
          type: string
          description: "태스크 타이틀"
      required:
        - id
        - title

